### ISSUE TITLE
Windows字体需要怎么安装？

### ISSUE THREAD

**Issue by lxj4321** [XiangyunHuang/bookdown-template#1]
字体已安装：  

![image](https://user-images.githubusercontent.com/19354503/164960643-21d3d85b-eaf6-4037-9453-ab18c4e09316.png)
build bs4_book 不成功，报错：  
`Error in check_font_path(regular, "regular") : 
  font file not found for 'regular' type
Calls: local ... <Anonymous> -> eval -> eval -> <Anonymous> -> check_font_path
ִֹͣ��
Error in Rscript_render(f, render_args, render_meta, add1, add2) : 
  Failed to compile index.Rmd
Calls: <Anonymous> ... render_book -> render_new_session -> Rscript_render
ִֹͣ��

Exited with status 1.`

添加字体报错：  

`sysfonts::[font_add](https://rdrr.io/pkg/sysfonts/man/font_add.html)(
  family = "Noto Serif",
  regular = "NotoSerif-Regular.ttf",
  bold = "NotoSerif-Bold.ttf",
  italic = "NotoSerif-Italic.ttf",
  bolditalic = "NotoSerif-BoldItalic.ttf"
)
sysfonts::[font_add](https://rdrr.io/pkg/sysfonts/man/font_add.html)(
  family = "Noto Serif CJK SC",
  regular = "NotoSerifCJKsc-Regular.otf",
  bold = "NotoSerifCJKsc-Bold.otf"
)`

`Error in check_font_path(regular, "regular") : 
  font file not found for 'regular' type`

**Comment by wenyaoleoliu** [comment]
我也是，同样的问题。

**Comment by XiangyunHuang** [comment]
我手边没有 Windows 系统，我也不知道怎么办？至于，怎么配置中文字体，可以看看 [showtext](https://github.com/yixuan/showtext) 包
